name: Notebook Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  session_6_run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert torch torchvision pytest numpy

    - name: Convert and Execute Notebook
      run: |
        jupyter nbconvert --to python ERA_V3_Session_6.ipynb
        python era_v3_session_6.py

    - name: Run Tests
      run: |
        pytest tests/test_model.py -v 