name: Notebook Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  session_6_run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert torch torchvision pytest numpy matplotlib tqdm torchsummary ipykernel

    - name: Convert and Execute Notebook
      run: |
        # Convert notebook to python script with special flags to handle IPython commands
        jupyter nbconvert --to python ERA_V3_Session_6.ipynb --template python_clean
        
        # Remove any IPython-specific commands from the converted script
        sed -i '/get_ipython/d' ERA_V3_Session_6.py
        
        # Add torchsummary import at the top of the file
        sed -i '1i\from torchsummary import summary' ERA_V3_Session_6.py
        
        # Rename and execute
        mv ERA_V3_Session_6.py era_v3_session_6.py
        python era_v3_session_6.py

    - name: Run Tests
      run: |
        pytest tests/test_model.py -v

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          final_accuracy.txt
          test-results.xml
        retention-days: 5